# Generated by Django 3.1.2 on 2020-12-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20201215_1622'),
        ('commentarea', '0008_auto_20201228_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentarea.paper')),
                ('user_list', models.ManyToManyField(related_name='my_chat_group', to='user.User')),
            ],
        ),
    ]
