# Generated by Django 3.1.2 on 2020-12-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShortComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('rose_number', models.IntegerField(default=0)),
                ('egg_number', models.IntegerField(default=0)),
                ('egg_user_list', models.ManyToManyField(related_name='egg_short_comment', to='user.User')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_short_comment', to='user.user')),
                ('rose_user_list', models.ManyToManyField(related_name='rose_short_comment', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='LongComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.CharField(max_length=255)),
                ('star_number', models.IntegerField(default=0)),
                ('comment_address', models.CharField(max_length=255)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_long_comment', to='user.user')),
                ('short_comment_list', models.ManyToManyField(to='commentarea.ShortComment')),
                ('star_user_list', models.ManyToManyField(related_name='star_long_comment', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='CreateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentarea.paper')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('long_comment_list', models.ManyToManyField(to='commentarea.LongComment')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentarea.paper')),
                ('short_comment_list', models.ManyToManyField(to='commentarea.ShortComment')),
                ('star_user_list', models.ManyToManyField(related_name='star_comment_area', to='user.User')),
            ],
        ),
    ]
