# Generated by Django 3.1.2 on 2020-12-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longcomment',
            old_name='abstract',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='longcomment',
            name='comment_address',
        ),
        migrations.AddField(
            model_name='longcomment',
            name='content',
            field=models.TextField(default=233),
            preserve_default=False,
        ),
    ]
