# Generated by Django 3.1.2 on 2020-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0003_commentarea_star_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='path',
        ),
        migrations.AddField(
            model_name='paper',
            name='paper',
            field=models.FileField(default=0, upload_to='papers'),
            preserve_default=False,
        ),
    ]
