# Generated by Django 3.1.2 on 2020-12-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0005_tests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tests',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
