# Generated by Django 3.1.2 on 2020-12-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentarea', '0006_auto_20201216_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paper', models.FileField(upload_to='paper')),
            ],
        ),
    ]
