# Generated by Django 3.1.3 on 2020-12-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_auto_20201213_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycommentarealist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starcommentlist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starpaperlist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staruserlist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
