"""
Django settings for pQper project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e!(a3$bthxm-cfc_l7of4yiqb22bfmokq#i+d3e_c7+=l54=ra'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'commentarea',
    'user',
    'star',
    'chatgroup',
    'SearchAndResults',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pQper.middleware.open_access_middleware',
]

ROOT_URLCONF = 'pQper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['frontend/dist', 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #addition place
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'pQper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'NAME': 'pQper',
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'wxz',
        'PASSWORD': '123456',
        'HOST': '39.105.19.68',
        
    }
}

X_FRAME_OPTIONS = 'SAMEORIGIN'
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/dist/static"),
]

# haystack 搜索引擎用
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
        'INCLUDE_SPELLING' : True,
    },
}

#自动更新索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'


# 文件存储路径和url
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL="/media/"


# 发送邮件
# 发送邮件设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False   # 是否使用TLS安全传输协议
EMAIL_USE_SSL = True    # 是否使用SSL加密，qq企业邮箱要求使用
# SMTP地址
EMAIL_HOST = 'smtp.qq.com'
# SMTP端口
EMAIL_PORT = 465
# 自己的邮箱
EMAIL_HOST_USER = '1192359897@qq.com'
# 自己的邮箱授权码，非密码
EMAIL_HOST_PASSWORD = 'wrhybjzdurjfbabd'
EMAIL_SUBJECT_PREFIX = 'pQper'



RSA_PUBLIC_KEY = "<MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAnAIl6VFrjwPg6v2qGMMywlOPoS/fqCk68MHt7RGroVlZJvucD7DqZJDrMyj0Y7VgCsnonsFRPlVB/PDOfywx8WT8UBzeLojjMIYIlET5QxAWvArcG6D6jiolcTDzyFPCjaeb2v4DkniqBvPaOitjm5TEI/wkV0wP9AzpbixDBQIDAQAB>"
 
RSA_PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\n" + "<MIICXAIBAAKBgQDAnAIl6VFrjwPg6v2qGMMywlOPoS/fqCk68MHt7RGroVlZJvucD7DqZJDrMyj0Y7VgCsnonsFRPlVB/PDOfywx8WT8UBzeLojjMIYIlET5QxAWvArcG6D6jiolcTDzyFPCjaeb2v4DkniqBvPaOitjm5TEI/wkV0wP9AzpbixDBQIDAQABAoGAVqeZu869x+Ne/lka6OUdJQASsiL1s+0nJ5Jb3Zxz/8CmvxpvxuW0VbALFxY8Tb9yQZR5BIQwO0oM95RCDtVeXwwg7pRXdIYbVj2WxeFsnD41ANpYg/UyPoG/Mduu4Cr+8zDR4B/CWzQju7vX1NcIxSByh+TATSeZFdXj+kNEgB0CQQDBY/CE+tDX7srtx4iQ3vWbLTggCROK4zUV6NvULatfg0MecnaehxFCt8wDTp2rKqQAHBS6dlElSICoUc9B7o7/AkEA/vdXebWXzM4ZZhTQ8t8lIvudJCb1cnbN3Z2gy09BRgyWQPKCOA75r+/2KeLteNKkxKepoJWwQiKPjncb81jx+wJAXA1RIEsu+4mbqGEQ3TxzlgCJNZ58YeDSlPI5KR7v8s/NNAHx+nV6PtKz1mMmY6IxXCgBqdvFtkRzkSsXx19hSwJABB+0Bn/taJ6cwo3ro0IAs8QmEoOezK8nPUJja2Zow91IQNyrRoTXfQUAkkTdWmrtx1B+6d4B78/nSoKarSDvKQJBAITD/OKVDqqhBlyRpNuRGauxPxk+i1MO/IHhNA4IAJT12HbMklaB42YS9YCe104AeQLENJON1HXw9hzEqYkLhtI=>" + "\n-----END RSA PRIVATE KEY-----"
