# Generated by Django 3.1.2 on 2020-12-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star_user_list',
            field=models.ManyToManyField(related_name='_user_star_user_list_+', to='user.User'),
        ),
    ]
