# Generated by Django 3.1.2 on 2020-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_star_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.FileField(default='avatars/default.jpg', upload_to='avatar'),
        ),
    ]
