# Generated by Django 3.1.4 on 2020-12-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201228_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='star_user_list',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
