# Generated by Django 3.1.3 on 2020-12-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_user_id'),
        ('commentarea', '0002_auto_20201212_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('user_id', models.IntegerField(default=0)),
                ('Star_User_List', models.ManyToManyField(to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='StarPaperList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('user_id', models.IntegerField(default=0)),
                ('Star_Paper_List', models.ManyToManyField(to='commentarea.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='StarCommentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('user_id', models.IntegerField(default=0)),
                ('Star_Comment_List', models.ManyToManyField(to='commentarea.LongComment')),
            ],
        ),
        migrations.CreateModel(
            name='MyCommentAreaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('user_id', models.IntegerField(default=0)),
                ('My_CommentArea_List', models.ManyToManyField(to='commentarea.CommentArea')),
            ],
        ),
    ]
