# Generated by Django 3.1.3 on 2020-12-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycommentarealist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='starcommentlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='starpaperlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='staruserlist',
            name='user_id',
        ),
    ]
